version: '3.8'

services:
  db:
    restart: always
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    restart: always
    image: ghcr.io/rodionmaulenov/gensslkey/web-gensslkey:v1.0.0
    command: /bin/sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn -w 3 scheduler.wsgi --bind 0.0.0.0:8000"
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

  nginx:
    restart: always
    image: ghcr.io/rodionmaulenov/gensslkey/nginx-gensslkey:v1.0.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
      - static:/usr/src/app/static
      - media:/usr/src/app/media

  certbot:
    restart: always
    image: certbot/certbot
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot


volumes:
  postgres_data:
  static:
  media: