version: '3.8'

services:
  web:
    image: web-prod
    build:
      context: ..
    volumes:
      - ..:/usr/src/app
      - ../static:/usr/src/app/static
      - ../media:/usr/src/app/media
    ports:
      - "8000:8000"
    env_file:
      ../.env

  celery:
    image: celery-prod
    build:
      context: ..
    volumes:
      - ..:/usr/src/app
    env_file:
      ../.env

  celery-beat:
    image: celery-beat-prod
    build:
      context: ..
    volumes:
      - ..:/usr/src/app
    env_file:
      ../.env

  nginx:
    image: nginx-prod
    build:
      context: ../nginx
      dockerfile: ../nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../static:/usr/src/app/static
      - ../media:/usr/src/app/media

  telegram:
    image: tel-prod
    build:
      context: ..
      dockerfile: Dockerfile.telegram
    volumes:
      - ..:/usr/src/app
    depends_on:
      - db
      - web
    env_file:
      - ../.env