version: '3.8'

services:

  nginx:
    image: ghcr.io/rodionmaulenov/timestamp/nginx-gensslkey:v1.0.0
    ports:
      - "80:80"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
