version: '3.8'

services:
  nginx:
    build:
      context: ../nginx
      dockerfile: ../nginx/Dockerfile.gensslkey
    image: nginx-gensslkey
    ports:
      - "80:80"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot


