name: For getting ssl key at first. Only for this goal.

on:
  push:
    branches:
      - gensslkey

jobs:
  build-dockers-images:
    name: Push images to GIT Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4.0.0

      - name: Install Docker Compose
        run: |
            sudo apt-get update
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo apt install docker-compose -y


      - name: Create .env file
        uses: skiddph/actions-env@v1.0.3

        env:
          ENV_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          ENV_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          ENV_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          ENV_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          ENV_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT}}
          ENV_DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE}}


      - name: Building docker images
        run: |
            docker-compose -f docker-compose.gensslkey.yaml build --no-cache

      - name: Log in to GitHub Packages
        run: echo ${{ secrets.GIT_REGISTRY_ACCESS_TOKEN }} | docker login ghcr.io -u initialdeploy --password-stdin

      - name: Push images to registry
        run: |
            docker push ghcr.io/gensslkey/onlyonce/initialdeployment/web-gensslkey:latest
            docker push ghcr.io/gensslkey/onlyonce/initialdeployment/nginx-gensslkey:latest